org: klippr
app: aws-node-http-api
service: aws-node-http-api

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"

package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json
    - README.md
    - npm-debug.log
    - .gitignore
    - .git/**
    - .serverless/**
    - .vscode/**
    - .DS_Store
    - .env
  include:
    - handler.js
    - node_modules/centra/**
    - node_modules/follow-redirects/**

functions:
  encode_pro:
    architecture: x86_64
    memorySize: 10240
    handler: handler.encode_pro
    url: true
    timeout: 600
    layers:
      - {Ref: FfmpegLambdaLayer}
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:076776954382:KlipprProQueue
          batchSize: 1

  encode_free:
    architecture: x86_64
    memorySize: 1500
    handler: handler.encode_free
    url: true
    timeout: 600
    layers:
      - {Ref: FfmpegLambdaLayer}
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:076776954382:KlipprFreeQueue
          batchSize: 1

layers:
  ffmpeg:
    path: layer

plugins:
  - serverless-offline
